const plugin = require('tailwindcss/plugin');

module.exports = plugin.withOptions(()=> {
    return function({addUtilities}) {
        addUtilities({
            '.bg-app': { background: 'var(--app-bg)' },
            '.bg-footer': { background: 'var(--footer-bg)' },
            '.bg-header': { background: 'var(--header-bg)' },
            '.bg-header-hover': { background: 'var(--header-bg-hover)' },
            '.bg-nav-bar': { background: 'var(--nav-bar-bg)' },
            '.bg-nav-bar-hover': { background: 'var(--nav-bar-bg-hover)' },
            '.bg-nav-option': { background: 'var(--nav-option-bg)' },
            '.bg-nav-option-hover': { background: 'var(--nav-option-bg-hover)' },
            '.bg-nav-profile-header': { background: 'var(--nav-profile-header-bg)' },
            '.bg-toolbar': { background: 'var(--toolbar-bg)' },
            '.bg-button-brand': { background: 'var(--button-brand-bg)' },
            '.bg-button-brand-hover': { background: 'var(--button-brand-bg-hover)' },
            '.bg-button-default': { background: 'var(--button-default-bg)' },
            '.bg-button-default-hover': { background: 'var(--button-default-bg-hover)' },
            '.bg-button-muted': { background: 'var(--button-muted-bg)' },
            '.bg-button-muted-hover': { background: 'var(--button-muted-bg-hover)' },
            '.bg-table-header': { background: 'var(--table-header-bg)' },
            '.bg-table-row-1': { background: 'var(--table-row-bg-1)' },
            '.bg-table-row-2': { background: 'var(--table-row-bg-2)' },
            '.bg-table-row-muted': { background: 'var(--table-row-muted-bg)' },
            '.bg-panel': { background: 'var(--panel-bg)' },
            '.bg-modal': { background: 'var(--modal-bg)' },
            '.bg-modal-blur': { background: 'var(--modal-blur-bg)' },
            '.bg-modal-header': { background: 'var(--modal-header-bg)' },
            '.bg-modal-footer': { background: 'var(--modal-footer-bg)' },
            '.bg-input': { background: 'var(--input-bg)' },
            '.bg-input-brand': { background: 'var(--brand-default)' },
            '.bg-input-muted': { background: 'var(--input-muted-bg)' },
            '.bg-success': { background: 'var(--success)' },
            '.bg-error': { background: 'var(--error)' },
            '.bg-warning': { background: 'var(--warning)' },
            '.bg-info': { background: 'var(--info)' },
            '.bg-debug': { background: 'var(--debug)' },
            '.bg-brand-lightest': { background: 'var(--brand-lightest)' },
            '.bg-brand-lighter': { background: 'var(--brand-lighter)' },
            '.bg-brand-light': { background: 'var(--brand-light)' },
            '.bg-brand': { background: 'var(--brand-default)' },
            '.bg-brand-dark': { background: 'var(--brand-dark)' },
            '.bg-brand-darker': { background: 'var(--brand-darker)' },
            '.bg-brand-darkest': { background: 'var(--brand-darkest)' },

            '.border-transparent': { borderColor: 'transparent' },
            '.border-default': { borderColor: 'var(--border)' },
            '.border-header': { borderColor: 'var(--header-border)' },
            '.border-footer': { borderColor: 'var(--footer-border)' },
            '.border-nav-divider': { borderColor: 'var(--nav-divider)' },
            '.border-nav': { borderColor: 'var(--nav-border)' },
            '.border-toolbar': { borderColor: 'var(--toolbar-border)' },
            '.border-nav-avatar': { borderColor: 'var(--nav-avatar-border)' },
            '.border-button-brand': { borderColor: 'var(--button-brand-border)' },
            '.border-button-brand-hover': { borderColor: 'var(--button-brand-border-hover)' },
            '.border-button-default': { borderColor: 'var(--button-default-border)' },
            '.border-button-default-hover': { borderColor: 'var(--button-default-border-hover)' },
            '.border-button-muted': { borderColor: 'var(--button-muted-border)' },
            '.border-button-muted-hover': { borderColor: 'var(--button-muted-border-hover)' },
            '.border-table': { borderColor: 'var(--table-border)' },
            '.border-table-divider': { borderColor: 'var(--table-divider)' },
            '.border-panel': { borderColor: 'var(--panel-border)' },
            '.border-panel-divider': { borderColor: 'var(--panel-divider)' },
            '.border-modal': { borderColor: 'var(--modal-border)' },
            '.border-input': { borderColor: 'var(--input-border)' },
            '.border-input-focus': { borderColor: 'var(--input-focus-border)' },
            '.border-success': { borderColor: 'var(--success)' },
            '.border-error': { borderColor: 'var(--error)' },
            '.border-warning': { borderColor: 'var(--warning)' },
            '.border-info': { borderColor: 'var(--info)' },
            '.border-debug': { borderColor: 'var(--debug)' },

            '.placeholder-input': { placeholderColor: 'var(--input-placeholder)' },

            '.ring-brand': { ringColor: 'var(--brand-default)' },
            '.ring-offset-input': { ringColor: 'var(--input-bg)' },

            '.text-default': { color: 'var(--default)' },
            '.text-muted': { color: 'var(--muted)' },
            '.text-link': { color: 'var(--link)' },
            '.text-link-hover': { color: 'var(--link-hover)' },
            '.text-footer': { color: 'var(--footer)' },
            '.text-header': { color: 'var(--header)' },
            '.text-header-muted': { color: 'var(--header-muted)' },
            '.text-header-link': { color: 'var(--header-link)' },
            '.text-header-link-hover': { color: 'var(--header-link-hover)' },
            '.text-nav-bar': { color: 'var(--nav-bar)' },
            '.text-nav-bar-hover': { color: 'var(--nav-bar-hover)' },
            '.text-nav-option': { color: 'var(--nav-option)' },
            '.text-nav-option-hover': { color: 'var(--nav-option-hover)' },
            '.text-nav-icon': { color: 'var(--nav-icon)' },
            '.text-nav-icon-hover': { color: 'var(--nav-icon-hover)' },
            '.text-nav-profile': { color: 'var(--nav-profile)' },
            '.text-nav-muted': { color: 'var(--nav-muted)' },
            '.text-toolbar': { color: 'var(--toolbar)' },
            '.text-button-brand': { color: 'var(--button-brand)' },
            '.text-button-brand-hover': { color: 'var(--button-brand-hover)' },
            '.text-button-brand-icon': { color: 'var(--button-brand-icon)' },
            '.text-button-brand-icon-hover': { color: 'var(--button-brand-icon-hover)' },
            '.text-button-default': { color: 'var(--button-default)' },
            '.text-button-default-hover': { color: 'var(--button-default-hover)' },
            '.text-button-default-icon': { color: 'var(--button-default-icon)' },
            '.text-button-default-icon-hover': { color: 'var(--button-default-icon-hover)' },
            '.text-button-muted': { color: 'var(--button-muted)' },
            '.text-button-muted-hover': { color: 'var(--button-muted-hover)' },
            '.text-button-muted-icon': { color: 'var(--button-muted-icon)' },
            '.text-button-muted-icon-hover': { color: 'var(--button-muted-icon-hover)' },
            '.text-table-header': { color: 'var(--table-header)' },
            '.text-table-header-hover': { color: 'var(--table-header-hover)' },
            '.text-table-row': { color: 'var(--table-row)' },
            '.text-table-row-muted': { color: 'var(--table-row-muted)' },
            '.text-panel': { color: 'var(--panel)' },
            '.text-panel-header': { color: 'var(--panel-header)' },
            '.text-input': { color: 'var(--input)' },
            '.text-input-muted': { color: 'var(--input-muted)' },
            '.text-modal': { color: 'var(--modal)' },
            '.text-modal-muted': { color: 'var(--modal)' },

            '.text-success': { color: 'var(--success)' },
            '.text-error': { color: 'var(--error)' },
            '.text-warning': { color: 'var(--warning)' },
            '.text-info': { color: 'var(--info)' },
            '.text-debug': { color:'var(--debug)' },

            '.text-brand-lightest': { color: 'var(--brand-lightest)' },
            '.text-brand-lighter': { color: 'var(--brand-lighter)' },
            '.text-brand-light': { color: 'var(--brand-light)' },
            '.text-brand': { color: 'var(--brand-default)' },
            '.text-brand-dark': { color: 'var(--brand-dark)' },
            '.text-brand-darker': { color: 'var(--brand-darker)' },
            '.text-brand-darkest': { color: 'var(--brand-darkest)' },
        });
    }
});